title: Erin's Webbie
author: Erin
email: erin_d_r@yahoo.com
description: > # this means to ignore newlines until "baseurl:"
  Really super cool website. You can't miss this, okay??

# social links
twitter_username: errn_errn # DO NOT include the @ character, or else the build will fail!
github_username:  ErrnErrn # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
